### ISSUE TITLE
Translate Python algorithms and comments to English. 

### ISSUE THREAD

**Issue by ricardocarva** [kelvins/algorithms-and-data-structures#183]
Please help translate the algorithms and comments in Python from Portuguese to English, as this would help increase the visibility of the repository, and it's the standard used by the company/people.

--

Por favor ajudem a traduzir os algoritmos e comentários em Python do português para o inglês, pois isso ajudaria a aumentar a visibilidade do repositório, e é o padrão utilizado por empresa/pessoas.

**Comment by ricardocarva** [comment]
Hi, @praptisharma28.
Welcome! Yes, it is open to contribute.
Once you open the Pull Request (PR), it goes through some validations on GitHub, and the PR is reviewed (approved/rejected). 
I do not see a PR submitted by you yet. Please confirm you have raised one. Also, if you offer a PR related to a particular issue, remember to add the Issue number in the PR's comments.

**Comment by kelvins** [comment]
Thanks @ricardocarva. @praptisharma28, [this](https://docs.github.com/en/get-started/quickstart/contributing-to-projects) article might also be helpful.

**Comment by lauicibovi23** [comment]
Hello, I would like to contribute to the improvement of this repository.
@ricardocarva @kelvins

**Comment by Aruuthakur** [comment]
Hi !  I would like to contribute to this repository

**Comment by SaiNikhil02** [comment]
@kelvins @ricardocarva can you please assign me this issue , I need to complete it as part of coursework

**Comment by lcgabaldon** [comment]
Hello! I would like to contribute.

**Comment by kelvins** [comment]
@lcgabaldon sure, please take a look at the [CONTRIBUTION](https://github.com/kelvins/algorithms-and-data-structures/blob/main/CONTRIBUTING.md) guidelines and feel free to send your PRs for review.

**Comment by kelvins** [comment]
Done by PR https://github.com/kelvins/algorithms-and-data-structures/pull/343
