### ISSUE TITLE
Translate Go algorithms and comments to English.

### ISSUE THREAD

**Issue by ricardocarva** [kelvins/algorithms-and-data-structures#184]
Please help translate the algorithms and comments in Go from Portuguese to English, as this would help increase the visibility of the repository, and it's the standard used by the company/people.

--

Por favor ajudem a traduzir os algoritmos e comentários em Go do português para o inglês, pois isso ajudaria a aumentar a visibilidade do repositório, e é o padrão utilizado por empresa/pessoas.

**Comment by thakurprathya** [comment]
Hello @ricardocarva, @kelvins,
if no one is working on this, please assign this to me.
I will try to translate the code.

**Comment by Tejjus** [comment]
Hey! Can I work on this?

**Comment by K11E3R** [comment]
I can work on this if none is assigned for it 👍🏽

**Comment by kelvins** [comment]
Feel free to work on this, but please submit small PRs so they are easier to review and merge.

**Comment by K11E3R** [comment]
locally i passed the golinter |> gofmt -w
