### ISSUE TITLE
Translate JavaScript algorithms and comments to English.

### ISSUE THREAD

**Issue by ricardocarva** [kelvins/algorithms-and-data-structures#186]
Please help translate the algorithms and comments in JavaScript from Portuguese to English, as this would help increase the visibility of the repository, and it's the standard used by the company/people.

--

Por favor ajudem a traduzir os algoritmos e comentários em JavaScript do português para o inglês, pois isso ajudaria a aumentar a visibilidade do repositório, e é o padrão utilizado por empresa/pessoas.

**Comment by Konebachirou** [comment]
Hello, I would like to work on your translation of the different algorithms from Portuguese to English if you are interested @ricardocarva @kelvins

**Comment by ricardocarva** [comment]
Hello, @Konebachirou .

Contributions are welcome. Please see [this ](https://github.com/kelvins/Algoritmos-e-Estruturas-de-Dados/blob/main/CONTRIBUTING.md) on how to contribute.

[This](https://docs.github.com/en/get-started/quickstart/contributing-to-projects) article might also be helpful.

**Comment by Konebachirou** [comment]
Hello @ricardocarva .
I would like to contribute by resolving issues that have not been resolved if this is possible of course.

**Comment by Tejjus** [comment]
Hey can I be assigned this issue?

**Comment by Konebachirou** [comment]
Hello, yes you can

**Comment by kelvins** [comment]
Done
