### ISSUE TITLE
Translate Rust algorithms and comments to English.

### ISSUE THREAD

**Issue by ricardocarva** [kelvins/algorithms-and-data-structures#188]
Please help translate the algorithms and comments in Rust from Portuguese to English, as this would help increase the visibility of the repository, and it's the standard used by the company/people.

--

Por favor ajudem a traduzir os algoritmos e comentários em Rust do português para o inglês, pois isso ajudaria a aumentar a visibilidade do repositório, e é o padrão utilizado por empresa/pessoas.

**Comment by thakurprathya** [comment]
Hello @ricardocarva, @kelvins,
if no one is working on this, please assign this to me.
I can try translating these.

**Comment by mangnez** [comment]
Hi @ricardocarva , @kelvins. I'm interested in working on this issue. If no one has been assigned yet, I'd appreciate the chance to contribute to it.

**Comment by kelvins** [comment]
Done
