### ISSUE TITLE
Translate Kotlin algorithms and comments to English. 

### ISSUE THREAD

**Issue by ricardocarva** [kelvins/algorithms-and-data-structures#190]
Please help translate the algorithms and comments in Kotlin from Portuguese to English, as this would help increase the visibility of the repository, and it's the standard used by the company/people.

--

Por favor ajudem a traduzir os algoritmos e comentários em Kotlin do português para o inglês, pois isso ajudaria a aumentar a visibilidade do repositório, e é o padrão utilizado por empresa/pessoas.

**Comment by Upendrafalak** [comment]
Hii, @ricardocarva i have opened a PR #205. Please check and let me know if any changes are required. Thanks!
