### ISSUE TITLE
Remove author signature from code

### ISSUE THREAD

**Issue by kelvins** [kelvins/algorithms-and-data-structures#210]
Some algorithms have author signature, like this one:

<img width="301" alt="image" src="https://github.com/kelvins/Algoritmos-e-Estruturas-de-Dados/assets/1009397/b797455e-361d-47b1-b2c5-652235461297">

I believe we could remove these signatures for some reasons:
- Most of them have already been changed by other contributors
- The code does not belong to a specific person
- Having an author may discourage others from contributing to that code
- Git keeps history if we need to blame someone :joy:

**Comment by akadeepesh** [comment]
Please assign this to me.

**Comment by 29deepanshutyagi** [comment]
kindly assign me this issue   @kelvins     , as i want to work on this issue.

**Comment by kelvins** [comment]
Hi @29deepanshutyagi, just the author 👍

**Comment by gh-adithya** [comment]
Hi! I would like to make my first contribution through this issue, can I have a go at it if the issues is still open?

**Comment by kelvins** [comment]
Done
