### ISSUE TITLE
Add Ring Buffer algorithm

### ISSUE THREAD

**Issue by kelvins** [kelvins/algorithms-and-data-structures#231]
Add ring buffer algorithm (circular buffer), ref: https://en.wikipedia.org/wiki/Circular_buffer

Related to https://github.com/kelvins/Algoritmos-e-Estruturas-de-Dados/issues/97

**Comment by WindowGenerator** [comment]
Hi!
Can I take this issue?
And by the way, in what language is it best to implement this algorithm? (I can implement it in (python, rust, js))

**Comment by kelvins** [comment]
Hi @WindowGenerator, sure. I would suggest starting with Python but feel free to use the language you feel more comfortable with.

**Comment by kelvins** [comment]
Closed by https://github.com/kelvins/algorithms-and-data-structures/pull/302
