### ISSUE TITLE
Split fibonacci into categories

### ISSUE THREAD

**Issue by kelvins** [kelvins/algorithms-and-data-structures#263]
There are different types of Fibonacci implementations in different languages.
Sometimes multiple implementations in the same file.

We could use the same approach used by "Min and Max" and split it into 3 categories:
- Fibonacci (Iterative)
- Fibonacci (Recursive)
- Fibonacci (Memoization)

This task is related to:
- [ ] Split the Fibonacci row (README) into 3 rows, as described above.
- [ ] Check the current implementation in each language and move it to the correct category.

**Comment by metacoder87** [comment]
I have submitted a series of pull requests that should close this issue. 

- [ ] Split the Fibonacci row (README) into 3 rows, as described above.
- [ ] Check the current implementation in each language and move it to the correct category.
- [ ] Filled in the missing implementations of the Fibonacci function in all languages.

**Comment by kelvins** [comment]
Hi @metacoder87, since all the PRs are related, and merging some of them alone will break the CI, I'll merge them into a separate feature branch, and open a new PR to merge them all into the `main` branch.
