### ISSUE TITLE
Implement Cocktail Shaker Sort Algorithm

### ISSUE THREAD

**Issue by akshayram1** [kelvins/algorithms-and-data-structures#352]
We need to implement the Cocktail Shaker Sort algorithm in our sorting library. This algorithm is a variation of the Bubble Sort that sorts a list by traversing it in both directions, allowing it to efficiently place unsorted elements in their correct positions, especially in nearly sorted lists.

**Comment by kelvins** [comment]
Thanks for contributing but we don't need to open an issue for this algorithm. It is already in the README list of sorting algorithms. You can contribute by submitting a PR implementing this algorithm in a language that is not yet implemented.
